name: Publish nuget

on:
  push:
    branches: [ "master" ]

env:
  working-directory: Sources
  release-directory: ./artifacts/package/release
  dotnet-version: 8.0.x

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: git config --global core.autocrlf input
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.dotnet-version }}

    - name: Restore dependencies
      run:
        working-directory: ${{ env.working-directory }}
      run: dotnet restore

    - name: Build
      run:
        working-directory: ${{ env.working-directory }}
      run: dotnet build -c Release /p:ContinuousIntegrationBuild=true --no-restore --verbosity normal

    - name: Test
      run:
        working-directory: ${{ env.working-directory }}
      run: dotnet test -c Release --no-build --verbosity normal

    - name: Publish to Nuget
      run:
        working-directory: ${{ env.working-directory }}
      run: dotnet nuget push ${{ env.release-directory }}/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

    - name: Publish to Nuget symbols
      run:
        working-directory: ${{ env.working-directory }}
      run: dotnet nuget push ${{ env.release-directory }}/*.snupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate